Initial commit of merge between unidata_20.3.2 and swit_23.4.1 of just the edexOsgi/ directory

diff --git a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/cleanup_svcbk b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/cleanup_svcbk
--- a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/cleanup_svcbk
+++ b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/cleanup_svcbk
@@ -3,19 +3,31 @@
 ##
 # This software was developed and / or modified by Raytheon Company,
 # pursuant to Contract DG133W-05-CQ-1067 with the US Government.
+<<<<<<< HEAD
 # 
+=======
+#
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 # U.S. EXPORT CONTROLLED TECHNICAL DATA
 # This software product contains export-restricted data whose
 # export/transfer/disclosure is restricted by U.S. law. Dissemination
 # to non-U.S. persons whether in the United States or abroad requires
 # an export license or other authorization.
+<<<<<<< HEAD
 # 
+=======
+#
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 # Contractor Name:        Raytheon Company
 # Contractor Address:     6825 Pine Street, Suite 340
 #                         Mail Stop B8
 #                         Omaha, NE 68106
 #                         402.291.0100
+<<<<<<< HEAD
 # 
+=======
+#
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 # See the AWIPS II Master Rights File ("Master Rights File.pdf") for
 # further licensing information.
 #
@@ -24,6 +36,7 @@
 ##
 #
 # SOFTWARE HISTORY
+<<<<<<< HEAD
 # Date         Ticket#    Engineer    Description
 # ------------ ---------- ----------- --------------------------
 # Feb 09, 2015  #4103     dgilling    Cleans up lock files, refactored to
@@ -32,6 +45,19 @@
 # Jan 07, 2019  #7704     randerso    Fix removal of backup rsync grids.
 # Apr 30, 2019  #7806     kbisanz     Do not remove files needed by Hazard
 #                                     Services.
+=======
+#
+# Date          Ticket#  Engineer  Description
+# ------------- -------- --------- --------------------------------------------
+# Feb 09, 2015  4103     dgilling  Cleans up lock files, refactored to support
+#                                  multiple svcbu sites.
+# Jul 15, 2016  5747     dgilling  Move edex_static to common_static.
+# Jan 07, 2019  7704     randerso  Fix removal of backup rsync grids.
+# Apr 30, 2019  7806     kbisanz   Do not remove files needed by Hazard Services.
+# Jun 29, 2021  8572     randerso  Pass failed site to serviceBackupUtil.sh
+# Aug 25, 2023  2028172  jkelmer   Added check to ensure Primary site
+#                                  configuration will not be deleted
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 #
 ##
 
@@ -52,11 +78,36 @@ fi
 CAPS_FAILED_SITE=`echo ${1} | tr [a-z] [A-Z]`
 LC_FAILED_SITE=`echo ${1} | tr [A-Z] [a-z]`
 
+<<<<<<< HEAD
 . ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env
 source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh
 
 configureLogging "svcbu_cleanup_svcbk" ${CAPS_FAILED_SITE}
 
+=======
+source ${AWIPS_HOME}/edex/bin/setup.env
+source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh ${CAPS_FAILED_SITE}
+
+configureLogging "svcbu_cleanup_svcbk" ${CAPS_FAILED_SITE}
+
+# Find primary sites, either from svcbu.properties
+# or AW_SITE_IDENTIFIER
+# sets PRI_SITES variable
+getPrimarySites
+
+# Determine which host service backup was run from
+# if my_site is the same as the failed site, stop
+for primary_site in "${PRI_SITES[@]}"
+do
+  primary_site=`echo $primary_site | tr [A-Z] [a-z]`
+  if [[ "$primary_site" = "${LC_FAILED_SITE}" ]]
+  then
+      echo "You cannot cleanup configuration data for your own site."
+      exit 1
+  fi
+done
+
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 #
 #-- Remove the locks directory
 #
diff --git a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids_to_failed_site b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids_to_failed_site
--- a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids_to_failed_site
+++ b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids_to_failed_site
@@ -24,28 +24,53 @@
 ##
 #
 # SOFTWARE HISTORY
+<<<<<<< HEAD
 # Date         Ticket#    Engineer    Description
 # ------------ ---------- ----------- --------------------------
 # Feb 09, 2015  #4103     dgilling    Refactored to support multiple svcbu 
 #                                     sites.
 # Mar 23, 2015  #4103     dgilling    Fix script for dual-domain.
 # Jul 15, 2016  #5747     dgilling    Move edex_static to common_static.
+=======
+#
+# Date          Ticket#  Engineer  Description
+# ------------- -------- --------- --------------------------------------------
+# Feb 09, 2015  4103     dgilling  Refactored to support multiple svcbu sites.
+# Mar 23, 2015  4103     dgilling  Fix script for dual-domain.
+# Jul 15, 2016  5747     dgilling  Move edex_static to common_static.
+# Jun 29, 2021  8572     randerso  Always export full domain. Pass failed site
+#                                  to serviceBackupUtil.sh
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 #
 ##
 
 
 if [ ${#AWIPS_HOME} = 0 ]
 then
+<<<<<<< HEAD
         path_to_script=`readlink -f $0`
 		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
 fi
 
 . ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env
 source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh
+=======
+    path_to_script=`readlink -f $0`
+    export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
+fi
+
+# $1 = Failed site
+FAILED_SITE=`echo ${1} | tr '[A-Z]' '[a-z]'`
+FAILED_CAPS_SITE=`echo ${1} | tr [a-z] [A-Z]`
+export FAILED_SITE
+
+source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh ${FAILED_CAPS_SITE}
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 
 if [ $# -ne 1 ]
 then
    echo "Incorrect number of arguments\nCorrect usage: export_grids_to_failed_site failed_site"
+<<<<<<< HEAD
    exit 1
 fi
 
@@ -54,6 +79,11 @@ FAILED_SITE=`echo ${1} | tr '[A-Z]' '[a-z]'`
 FAILED_CAPS_SITE=`echo ${1} | tr [a-z] [A-Z]`
 export FAILED_SITE
 
+=======
+    exit 1
+fi
+
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 # Create the log file
 configureLogging "svcbu_export_bksite_grids" ${FAILED_SITE}
 
@@ -62,12 +92,18 @@ lock_file=$(getLockFile "exportBkSiteGrids" ${FAILED_SITE})
 lock_status=$(isOperationInProgress "exportBkSiteGrids" ${FAILED_SITE})
 if [[ "${lock_status}" = "true" ]]
 then
+<<<<<<< HEAD
 	echo "Cannot export grids back to ${FAILED_SITE}.  Export grids process already in progress!"
 	exit 1
+=======
+    echo "Cannot export grids back to ${FAILED_SITE}.  Export grids process already in progress!"
+    exit 1
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 fi
 
 echo "IN_PROGRESS" > ${lock_file}
 
+<<<<<<< HEAD
 #
 # If this is a non-wfo/non-rfc site, they may not have an edit area for clipping - handle it
 #
@@ -77,13 +113,19 @@ else
    SVCBU_MASK="-m $SVCBU_GRIDAREA"
 fi
 
+=======
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 echo "Starting exporting grids..."
 
 OUTPUT_DIR=$(getTempDirectory "export_grids_to_failed_site" ${FAILED_SITE})
 
 #Starting ifpnetCDF to pack the grids
 echo "Running ifpnetCDF..."
+<<<<<<< HEAD
 ${GFESUITE_BIN}/ifpnetCDF -o ${OUTPUT_DIR}/${FAILED_SITE}Grd.netcdf -h $SVCBU_HOST -r $CDSPORT -d ${FAILED_CAPS_SITE}_GRID__Official_00000000_0000 -k -t -c ${SVCBU_MASK}
+=======
+${GFESUITE_BIN}/ifpnetCDF -o ${OUTPUT_DIR}/${FAILED_SITE}Grd.netcdf -h $SVCBU_HOST -r $CDSPORT -d ${FAILED_CAPS_SITE}_GRID__Official_00000000_0000 -k -t -c
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 if [ $? -ne 0 ]; then
     echo "ERROR: ifpnetCDF failed."
     echo "FAILED" > ${lock_file}
diff --git a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/process_grids b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/process_grids
--- a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/process_grids
+++ b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/process_grids
@@ -24,6 +24,7 @@
 # This is run at the backup site to merge the failed site's grids into the 
 # Fcst database.
 #
+<<<<<<< HEAD
 #     SOFTWARE HISTORY
 #    
 #    Date            Ticket#       Engineer       Description
@@ -32,12 +33,24 @@
 #    02/12/15        4103          dgilling       Consolidated process_grids and
 #                                                 proc_receive_grids into 1 script.
 #    08/01/2017      6337          randerso       Use more restrictive file permissions
+=======
+# SOFTWARE HISTORY
+#
+# Date          Ticket#  Engineer       Description
+# ------------- -------- -------------- ----------------------------------------
+# Jun 16, 2014  3276     randerso       Added -T to iscMosaic call
+# Feb 12, 2015  4103     dgilling       Consolidated process_grids and
+#                                       proc_receive_grids into 1 script.
+# Aug 01, 2017  6337     randerso       Use more restrictive file permissions
+# Jun 29, 2021  8572     randerso       Pass site ID to serviceBackupUtil.sh
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 #
 ##############################################################################
 
 
 if [ ${#AWIPS_HOME} = 0 ]
 then
+<<<<<<< HEAD
         path_to_script=`readlink -f $0`
 		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
 fi
@@ -49,6 +62,19 @@ source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh
 # $2 = site ID for the file
 import_file=${1}
 SITE_ID=`echo ${2} | tr '[A-Z]' '[a-z]'` 
+=======
+    path_to_script=`readlink -f $0`
+    export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
+fi
+
+# $1 = Path to packaged netcdf file received from MHS
+# $2 = site ID for the file
+import_file=${1}
+SITE_ID=`echo ${2} | tr '[A-Z]' '[a-z]'`
+SITE_ID_CAPS=`echo ${2} | tr [a-z] [A-Z]`
+
+source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh ${SITE_ID_CAPS}
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 
 # Create the log file
 configureLogging "svcbu_receive_grids" ${SITE_ID}
@@ -58,7 +84,11 @@ lock_file=$(getLockFile "importGrids" ${SITE_ID})
 lock_status=$(isOperationInProgress "importGrids" ${SITE_ID})
 if [[ "${lock_status}" = "false" ]]
 then
+<<<<<<< HEAD
 	echo "Lock file not present for importing grids!  Cannot continue!"
+=======
+    echo "Lock file not present for importing grids!  Cannot continue!"
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
     echo "FAILED" > ${lock_file}
     exit 1
 fi
@@ -87,9 +117,15 @@ sleep 2
 tar -xOf ${SITE_ID}Grd.tar > ${SITE_ID}Grd.netcdf.gz --exclude siteID.txt
 if [ $? -ne 0 ]
 then
+<<<<<<< HEAD
 	echo "ERROR: tar failed to untar ${SITE_ID}Grd.tar."
     echo "FAILED" > ${lock_file}
 	exit 1
+=======
+    echo "ERROR: tar failed to untar ${SITE_ID}Grd.tar."
+    echo "FAILED" > ${lock_file}
+    exit 1
+>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
 fi
 rm -f  ${SITE_ID}Grd.tar
 
